# Generated by Django 4.0.5 on 2022-07-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='btn',
            field=models.CharField(default='Concluir', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(default='Ativa', max_length=10),
        ),
    ]
